title: Autumn Conference 2022
description: >- # this means to ignore newlines until "baseurl:"
  Motions for the Green Party 2022 Autumn Conference, from the Standing Orders Committee.
email: mailto:soc@greenparty.org.uk
baseurl: "/agenda" # the subpath of your site, e.g. /blog
url: "http://greencoordinate.co.uk" # the base hostname & protocol for your site, e.g. http://example.com

# Switches
create_sections: false
show_coproposers: false
affiliated_threshold: 4
unaffiliated_threshold: 12
archive: false
fixed_homepage: https://www.greencoordinate.co.uk/agenda

# Build settings
sass:
  sass_dir: /css/

collections:
  amendments:
    output: false
  motions:
    output: true
    permalink: :collection/:name/


defaults:
  -
    scope:
      path: ""
      type: "motions"
    values:
      layout: "motion"
      toc: true