backend:
  name: github
  repo: AshRouth/SOC
  branch: ash
media_folder: 'files'
site_url: https://illustrious-mousse-b63d64.netlify.app/
collections:
  - name: 'motions'
    label: 'Motions'
    label_singular: 'Motion'
    folder: '_motions/'
    create: true
    summary: "#{{motion_code.section}}{{motion_code.number}} {{title}}"
    editor:
      preview: false
    sortable_fields: ['motion_code.number']
    view_groups:
      - label: Section
        field: motion_code.section
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'motion'
      - label: 'TOC'
        name: 'toc'
        widget: 'hidden'
        default: 'true'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Motion Code'
        name: 'motion_code'
        widget: 'object'
        summary: '#{{fields.section}}{{fields.number}}'
        fields:
          - label: "Section"
            name: "section"
            widget: "string"
            required: false
          - label: "Number"
            name: "number"
            widget: "number"
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options:
          - { label: "Draft", value: "draft" }
          - { label: "Final", value: "final" }
          - { label: "To be debated", value: "tbd" }
          - { label: "Passed", value: "passed" }
          - { label: "Defeated", value: "defeated" }
          - { label: "Referred", value: "referred" }
          - { label: "Not debated", value: "notdebated" }
      - { label: 'Green Spaces Link', name: 'spaces', widget: 'string', required: false }
      - { label: 'Coproposer Count', name: 'coproposers', widget: 'number', required: false }
      - { label: 'Affiliated Motion', name: 'affiliated', widget: 'boolean', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }