backend:
  name: github
  repo: rileyrouth/greencoordinate
  branch: ash
media_folder: 'assets/uploads'
site_url: https://fantastic-crepe-2e5bfe.netlify.app
collections:
  - name: 'motions'
    label: 'Motions'
    label_singular: 'Motion'
    folder: '_motions/'
    create: true
    summary: "#{{motion_code.section}}{% if motion_code.number < 10 %}0{% endif %}{{ motion_code.number }} {{title}}"
    editor:
      preview: false
    sortable_fields: ['title', 'motion_code.section']
    view_groups:
      - label: Section
        field: motion_code.section
        # groups items based on the value matched by the pattern
        pattern: \w+
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'motion'
      - label: 'TOC'
        name: 'toc'
        widget: 'hidden'
        default: 'true'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Motion Code'
        name: 'motion_code'
        widget: 'object'
        summary: '#{{fields.section}}{{fields.number}}'
        fields: 
          - label: "Section"
            name: "section"
            widget: "string"
          - label: "Number"
            name: "number"
            widget: "number"
      - { label: 'Status', name: 'status', widget: 'string' }
      - { label: 'Green Spaces Link', name: 'spaces', widget: 'string' }
      - { label: 'Coproposer Count', name: 'coproposers', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
